### ISSUE TITLE
Alien Syndrome character gets stuck

### ISSUE THREAD

**Issue by jotego** [jotego/jts16#1]
Some the main character animation will freeze and it will always show at the middle of the screen. Seen in System 16B versions. Confirmed in version 1201f97

**Comment by jotego** [comment]
Seen in all versions.

**Comment by jotego** [comment]
Still happens in da29983

**Comment by jotego** [comment]
Tested in da29983
This doesn't happen in sets:
1, 3, 4, 7
The commit da29983 made the DTACKn signal generation more strict. That seems to have fixed this bug.

**Comment by Turbochop** [comment]
The issue seems to have returned. It is reliably triggered by spamming direction keys. sometimes the game will even lock up completely.
