### ISSUE TITLE
Golden Axe slowdown

### ISSUE THREAD

**Issue by ArtemioUrbina** [jotego/jts16#11]
Using Golden Axe set 4, Japan, FD1094 317-0121 (but happens on all versions) when compared to the Arcade PCB there are big slow down segments when several sprites are shown at once. It is very evident in the following video but happens almost everywhere.

[Video with issue](https://youtu.be/QvZaRKwWEbk?t=10)

Used my own ROMs from Japan set on the MiSTer FPGA. Both were running at teh same time and I tried to sync them as best as I could using two capture cards and both systems.

You can see the MiSTer Core slows down compared to the PCB. Core updated on May 7th 2022. PCB is running stock FD1094 317-0121 CPU.

Difference can be seen when pushing right on both the arcade PCB and Mister FPGA at the same time.

**Comment by gyurco** [comment]
I confirm this, it starts to be noticeable in stage 2 (Turtle Village), when the dragons starts to appear.

**Comment by ArtemioUrbina** [comment]
Confirmed
