### ISSUE TITLE
MRAs with MCU FD1089A show black screen with the release of 08/07/2022

### ISSUE THREAD

**Issue by wwark** [jotego/jts16#14]
I can be checked with those two MRAs
https://raw.githubusercontent.com/jotego/jtbin/master/mra/_alternatives/_Alien%20Syndrome/Alien%20Syndrome%20(set%206%2C%20Japan%2C%20new%2C%20System%2016B%2C%20FD1089A%20317-0033).mra
https://raw.githubusercontent.com/jotego/jtbin/master/mra/_alternatives/_Aurail/Aurail%20(set%201%2C%20Japan)%20(FD1089A%20317-0167).mra

Thanks

**Comment by jotego** [comment]
Thank you. I have consolidated the two S16B core variations to avoid further problems like this. The new files are available in the usual place.

**Comment by wwark** [comment]
It seems you miss to add the jt16b core of 20220709 on jtbin
Thank you !

**Comment by jotego** [comment]
I can see it in JTBIN, at least the [MiSTer](https://github.com/jotego/jtbin/blob/master/mister/s16b/releases/jts16b_20220709.rbf) version.

**Comment by wwark** [comment]
I rechecked and found it ... sorry maybe pass it when i scroll mra files the first time !

**Comment by jotego** [comment]
I'm glad you found it :-)
