### ISSUE TITLE
check golden axe and tough turf after recent update

### ISSUE THREAD

**Issue by jotego** [jotego/jts16#18]

**Comment by shuffle5** [comment]
There seems to be an issue on the attract screen where it shows the drawing of the character - it is corrupted now. AX=BATTLER etc.    the pixels are not correct any more. 
![IMG_2023](https://user-images.githubusercontent.com/73855651/192160426-bbdbc14e-3d4f-438b-9e05-b2794e1c6e2c.jpg)
