### ISSUE TITLE
[goldnaxe1] game locks in stage 2

### ISSUE THREAD

**Issue by jotego** [jotego/jts16#5]
If the enemy is pushed off the cliff, the game doesn't let you advance. The go sign never shows up. Slashing the enemy lets you advance. Either killing method is ok in MAME.

![0001](https://user-images.githubusercontent.com/1863036/163668497-12d30d7a-a319-406b-8f5b-2a0ca91afd68.png)

Music gets corrupted too.

First seen in 7dc5bde

**Comment by sqwirral** [comment]
`Golden Axe (set 1, World) (FD1094 317-0110)` - Crash (tested 2 times)
`Golden Axe (set 2, US) (8751 317-0112)` - No crash (tested 3 times)
`Golden Axe (set 3, World) (FD1094 317-0120)` - No crash (tested 1 time)
`Golden Axe (set 4, Japan) (FD1094 317-0121)` - No crash (tested 1 time)
`Golden Axe (set 5, US) (FD1094 317-0122)` - Crash (tested 1 time)

**Comment by shuffle5** [comment]
i tried set 6 US version with ax battler, pushing off cliff with shoulder - no crash (2 times tested)

**Comment by jotego** [comment]
It locks even with `git co 8072eb3 -- jtframe_68kdtack.v` on JTFRAME

**Comment by jotego** [comment]
Retested in 29152a4 after the improved jtframe_68kdtack. It still happens.

**Comment by jotego** [comment]
Fixed in 40b01df
The /IPL2 interrupt line was latched, but it shouldn't be
