### ISSUE TITLE
261 lines/frame

### ISSUE THREAD

**Issue by paulb-nl** [jotego/jts16#7]
Currently the core outputs 261 lines @ 60.28Hz. 

I think it is more likely to be 262 lines @ 60.05Hz. This is 16.65ms per frame which is closer to the 16.64ms period shown in your IPL2 scope measurement.
https://github.com/jotego/jts16/blob/master/doc/scope/IPL2.png

**Comment by jotego** [comment]
Indeed, 262 is the right number. I'll update the core. Thank you
![S16_VINT_period](https://user-images.githubusercontent.com/1863036/164488495-c28316cb-08c6-43d6-a1d5-bb0ff5f8a82e.png)

**Comment by jotego** [comment]
fixed in 1bee3db
